# Generated by Django 5.0.1 on 2025-05-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='order_documents/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transition_point',
            field=models.CharField(choices=[('57505', 'Нур Жолы'), ('57504', 'Достык (Железнодорожный)'), ('57503', 'Алаколь (Автомобильный)'), ('50709', 'Актау Морпорт'), ('55302', 'Алматы ЦТО'), ('57301', 'Бахты')], default='created', max_length=255),
        ),
    ]
