# Generated by Django 5.0.1 on 2025-05-11 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_order_document_alter_order_transition_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='document',
        ),
    ]
