# Generated by Django 5.0.1 on 2025-05-11 21:47

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_remove_order_file_orderfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfile',
            name='file',
            field=models.FileField(upload_to=crm.models.order_file_upload_path),
        ),
    ]
