# Generated by Django 5.0.1 on 2025-05-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_orderfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transition_point',
            field=models.CharField(max_length=255),
        ),
    ]
