# Generated by Django 5.2 on 2025-05-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_order_transition_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
