# Generated by Django 5.2 on 2025-06-23 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_order_car_weight_order_currency_order_loaded_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(help_text='Номер машины', max_length=20, unique=True)),
                ('trailer_number', models.CharField(blank=True, help_text='Номер прицепа', max_length=20, null=True)),
                ('car_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trailer_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('driver_number', models.CharField(blank=True, help_text='Номер телефона водителя', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='car_weight',
        ),
        migrations.RemoveField(
            model_name='order',
            name='trailer_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='trailer_weight',
        ),
        migrations.AddField(
            model_name='order',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='crm.transport'),
        ),
    ]
