# Generated by Django 5.2 on 2025-06-23 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_transport_remove_order_car_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='car_number',
        ),
    ]
