# Generated by Django 5.2 on 2025-06-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_remove_order_car_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='loaded_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='car_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='trailer_number',
            field=models.CharField(help_text='Номер прицепа', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='trailer_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
